/*
 * by KK
 */
#include <st7735s.h>

 void __attribute__((weak)) _init(void){}      // needed for startup generated by cubeIDE
 void __attribute__((weak)) SystemInit(void){} // needed for startup generated by cubeIDE

void main(void)
{
  ST7735S_Init();

  ST7735S_FillScreen(0xFF0000);

  ST7735S_FillRect(0,0,70,80,0x0000AB);
  ST7735S_WriteString("Hello World!", 20, 20, 0x00FF00, 0x000000);
  while (1);
}


